### ISSUE TITLE
Create Roadmap View

### ISSUE THREAD

**Issue by vincent6767** [o3de/sig-release#127]
Hi! SIG release is working to help the O3DE community to get visibility of the O3DE roadmap. Full context can be read here: https://github.com/o3de/sig-release/issues/79. 

In order to achieve that goal, we need your help to create the roadmap for your SIG by **February 6th, 2023**, and start giving brief updates about the roadmap items at the **Joint TSC meeting on February 28th, 2023**. Instruction to create the roadmap view can be read in the RFC section "Roadmap Review in TSC monthly meeting".

Let me know if you have any concerns with the dates or any questions about the ask!

**Comment by vincent6767** [comment]
@tonybalandiuk Are there any updates on this area?

**Comment by tonybalandiuk** [comment]
@vincent6767  See https://github.com/orgs/o3de/projects/29/views/1  - any issues you think it's missing?

**Comment by vincent6767** [comment]
@tonybalandiuk Do we want to put [streamline the release notes process](https://github.com/o3de/sig-release/discussions/107) as part of the roadmap item? Other than that, looks good to me!

**Comment by vincent6767** [comment]
I'll move forward adding that as part of our roadmap.
