### ISSUE TITLE
Joint TSC Meeting - January 31st, 2023

### ISSUE THREAD

**Issue by vincent6767** [o3de/sig-release#131]
What we did last month
1. We started the RFC SIGs roadmap this month. The target is to have all SIGs create their roadmap by February 6th, 2023. You can track the progress here: https://github.com/o3de/sig-release/issues/128
2. Asked TSC to add another agenda for each SIG chair to represent briefly their roadmap in the TSC meeting. Are there any concerns if we go that way?
3. Started documenting the current release process for helping any RM to get on board.
4. Started discussion about what the repositories included in the process. This started due to an O3DE-extras discussion.

What we're going next month
1. Define SIG release roadmap
2. Partner with each SIG to create a roadmap for their respective area.
3. Partner with docs-community, TSC, and marketing to surface this into O3DE websites.
4. Decide criteria for repos to be included in a release. https://github.com/o3de/sig-release/discussions/129
5. Decide whether to include o3des-extras as part of the O3DE release or not.

**Comment by vincent6767** [comment]
@tonybalandiuk Feel free to add or edit anything that I miss.

**Comment by tonybalandiuk** [comment]
looks good @vincent6767  Thanks for putting this together
