### ISSUE TITLE
O3DE Release 23.5.0  (scheduled for May 3, 2023) - Key Information

### ISSUE THREAD

**Issue by tonybalandiuk** [o3de/sig-release#133]
This issue is a single destination for all things related to the O3DE 23.05.0 Release. This issue will be updated as information changes. We will use this issue to surface questions and answer them so the entire community is aware of what to expect for the release.

**O3DE 23.05.0 About this Release**
O3DE 23.05.0 will be the first major release of O3DE in 2023. The previous release was the 22.10.0 major release (Oct 2022). The 23.05 release will contain all of the features in the dev branch as of (stabilization date) Pacific time. 
Per our release naming standards, when referencing the release in technical documentation, the release should be referred to as "23.05.0".
For marketing and general discussion, it is acceptable to refer to the release as "23.05". 

**Release Managers**
Release Manager: TBD
Co-Release Manager:  TBD
Documentation Project Manager: @chanmosq 

**Release Project Board**
https://github.com/orgs/o3de/projects/48/views/1

**Feature List**
Coming soon

**Release Notes**
Coming soon

**Stabilization Branch**
https://github.com/o3de/o3de/tree/stabilization/2305
https://github.com/o3de/o3de-multiplayersample/tree/stabilization/2305
https://github.com/o3de/o3de-multiplayersample-assets/tree/stabilization/2305
https://github.com/o3de/o3de-netsoaktest/tree/stabilization/2305
https://github.com/o3de/o3de.org/tree/stabilization/2305

**Stabilization Bug Reporting**
In the stabilization branch, any bugs found should get the "Release/2305" milestone applied. 

**Bug Tracking**
O3DE main repo - Bugs are being tracked with the [Release/2305 Milestone.] (milestone link)
Atom Sample Viewer repo - TBD

**Release Schedule with Exception Process for Submitting Code to the Stabilization Branch**
As documented in the below table, submissions to the stabilization branch will be subject to an Exception Process, (link to exception process)

**Stabilization/2305 - Exception Requests**
You can access the board [here](https://github.com/orgs/o3de/projects/49/views/1)

Date | Description | Bug Fixes  Allowed in Stabilization Branch| New Features Allowed in Stabilization Branch
-- | --|--|--
Mar 1| Feedback period closed. No SIGs raised any concerns with release schedule | N/A | N/A
TBD| Marketing committee confirmed ok with proposed release schedule | N/A | N/A
TBD |Release managers posted, empty project board set up.| N/A| N/A
Mar 15, 10am Pacific | Stabilization Branches created for the following repositories: o3de, o3de-multiplayersample, o3de-netsoaktest, o3de-extras . | N/A | N/A
Mar 15, 10am Pacific | (Docs) Stabilization branch created | N/A | N/A
Mar 15 through Apr 11, 2023 | Stabilization Period| Yes | Yes, exception process is not required.
Apr 12, 2023 | Code Freeze on Major Bugs and below| Beginning this date,  Blocker and Critical bugs are allowed without the exception process. Major bugs or below requires an exception.| No
Apr 12, 2023| (Docs) Versioned API reference generation. A PR will be created by this date. Two approvals are needed from the [o3de.org](http://o3de.org/)'s standard reviewer pool. The PR should be merged by April 27. We will continue to accept changes until April 26. | N/A | N/A
April 19| (Docs) Release Notes Finalized (features + known issues. A PR will be created by this date. A reviewer from sig-docs-community and sig-release are needed to approve the PR. The PR should be merged by April 27. We will continue to accept changes until April 26. | N/A | N/A
Apr 21, 2023  5pm Pacific| Code Freeze on Critical Bugs and below | Beginning this date, only Blocker bugs are allowed via the exception process. No other bug fixes allowed.| No 
April 21 through Apr 26, 2023| QA Final Pass| Blocker bugs are still allowed via the exception process, with risk of delaying the release.| No
Apr 27, 2023|Release considered "stable", all blocker/critical issues are resolved. | No| No
May 3, 2023|  Release tasks are done. Binaries posted, code merged. The following repositories will be tagged:o3de, o3de-multiplayersample, o3de-netsoaktest, o3de-extras . | No | No
TBD | 23.05.0 Release Marketing Announcement | No | No

**Comment by vincent6767** [comment]
I think this discussion will be a release blocker before we complete the next release: https://github.com/o3de/sig-release/discussions/129. @tonybalandiuk Thoughts?

**Comment by vincent6767** [comment]
The other question is are we going to wait for RM from Linux Foundations or just proceeds with the date regardless?

**Comment by vincent6767** [comment]
Oh, I think this could be a roadmap item for the SIG release. Any concerns if I label this as a kind/roadmap? @tonybalandiuk

**Comment by tonybalandiuk** [comment]
@vincent6767  good idea. Added.

**Comment by lmbr-pip** [comment]
Minor: Schedule should include creation of stabilization branches in O3DE projects that O3DE considers in scope for release ie o3de-multiplayersample.

**Comment by tonybalandiuk** [comment]
@lmbr-pip  great callouts, thanks

> Minor: Schedule should include creation of stabilization branches in O3DE projects that O3DE considers in scope for release ie o3de-multiplayersample, o3de-extras, planet storm, atom-sample-viewer.

Added

> Similar note is required for when these projects tag / branch to match release.

Added

Current plans are that the release will include the following 4 repos :
o3de
o3de-multiplayersample
o3de-netsoaktest
o3de-extras 

(atom-sample-viewer has been dropped BTW). 

You mentioned planet storm. If you think planet storm should be included, can you open up an issue for sig-release indicating some background and reasoning? We need a record of that request, need to decide on it, update the process documentation, etc. Thanks.

**Comment by chanmosq** [comment]
For constructing the feature list, which results in the Release Notes, I suggest we have another issue where SIGs can list their updates and known issues. 

Here are templates SIGs can follow: 

1. **Feature update template**: 
  ```
### sig-*
- <summary><pr>
- <summary>
	- <summary><pr>
	- <summary><pr>
```
  - `<summary>`: A 1-3 sentence summary of the update. Provide context as needed, allowing people to understand what's changed.
  - `<pr>`: Link(s) to the GitHub PR

2. **Known issues template**: 
  ```
### Feature
- <summary><issue>
```
  - `Feature`: What O3DE feature this corresponds to
  - `<summary>`: A 1-3 sentence summary of the issue. Provide context as needed, allowing people to understand what's the problem.
  - `<issue>`: Link(s) to the GitHub Issue.
It's best if all information, such as details and ways to work around it, are in the GitHub issue. If for any reason an issue is present, please provide the details here.

**Comment by hultonha** [comment]
@chanmosq Would it be possible to please include a full example(s) of what this might look like, the snippets above are still a bit cryptic to me.

Also something our teams do quite a lot are work on larger initiatives that might contain many PRs that then get referenced from an issue of `kind/roadmap` (e.g. https://github.com/o3de/o3de/issues/10666 - scroll down to see all linked PRs). To keep the Release Notes at a reasonable length can we take this route for the majority of issues and allow people to look at the roadmap initiatives to see relevant PRs? Thanks!

**Comment by hultonha** [comment]
One other question @chanmosq is if we would like to link to relevant docs pages from the release notes, how should we refer to them? Right now for new docs I'd need to use a link such as https://development--o3deorg.netlify.app/docs/learning-guide/tutorials/assets/physx-colliders/, but I believe this should change to a url resembling this when the release is live https://www.o3de.org/docs/learning-guide/tutorials/assets/physx-colliders/. When creating the release notes what's the best approach to take so we can link to the correct docs pages? Thank you!

**Comment by vincent6767** [comment]
> To keep the Release Notes at a reasonable length can we take this route for the majority of issues and allow people to look at the roadmap initiatives to see relevant PRs?

I agree with this. One of the reasons we push for the roadmap item is to reference it in the release notes without mentioning all of its subtasks.

**Comment by vincent6767** [comment]
@tonybalandiuk FYI, I added the link to the exception board in the issue description: https://github.com/orgs/o3de/projects/49/views/1

Also, can you remind me where is the release board?

**Comment by tonybalandiuk** [comment]
@vincent6767  I updated the issue description to link to the release board.

**Comment by chanmosq** [comment]
@hultonha  @vincent6767 Sorry for the delayed response as this slipped my notifications. 

> Would it be possible to please include a full example(s) of what this might look like, the snippets above are still a bit cryptic to me.

Most of the [past release notes](https://www.o3de.org/docs/release-notes/22-10-0/) follow this pattern. For example:
```
## Features and bug fixes 
### sig-graphics-audio
- Added a new Shadow Bias flag for parallax materials to deal with shadow acne on parallax surfaces.
- Added minimum and maximum sliders to the Pass Tree Debug tool to support trimming the color output for increased contrast of fine details. [#9292](https://github.com/o3de/o3de/pull/9292)
- Added averages to the CPU Profiler. [#10253](https://github.com/o3de/o3de/pull/10253)

## Known issues
### Script Canvas
- Saving changes to a script that's incompatible with the interpreter can crash O3DE Editor. [#11747](https://github.com/o3de/o3de/issues/11747)
```
- The "Shadow Bias flag" one would be better if it has a link to the PR (or roadmap with the list of PRs)
- The others look good

> To keep the Release Notes at a reasonable length can we take this route for the majority of issues and allow people to look at the roadmap initiatives to see relevant PRs?

Yes! Please link to the roadmap issue instead

> When creating the release notes what's the best approach to take so we can link to the correct docs pages?

Here are two examples from the past release notes. You can hyperlink relevant text with the link to the docs, such as the "Python-based tests" example. Or you can insert the title and link to the docs into a separate sentence that starts with "See ..." or "Refer to ...".
```
- Material Editor test tools now support [Python-based tests](https://www.o3de.org/docs/user-guide/testing/parallel-pattern/), expanding automated testing to more parts of O3DE. This helps O3DE contributors efficiently verify and improve the behavior of the Material Editor. 

- The O3DE Motion Matching Gem is ready for experimental use. See [Motion Matching in O3DE, a Data-Driven Animation Technique](https://www.o3de.org/blog/posts/blog-motionmatching/) for more details. [#10665](https://github.com/o3de/o3de/issues/10665)

```

**Comment by vincent6767** [comment]
@tonybalandiuk To confirm. Will we close this once the post-tasks are done?

**Comment by tonybalandiuk** [comment]
@vincent6767  I think we can close this now since the release is done.
