### ISSUE TITLE
Update ReadMe

### ISSUE THREAD

**Issue by aFinchy** [o3de/sig-release#150]
Hi SIG Release Members,

To assist new and existing members, I would like to request that all SIG repositories update their readme files with comprehensive information. Please include any and all details that you think would be helpful.

If you require examples, please refer to the following repositories as references:

https://github.com/o3de/sig-docs-community
https://github.com/o3de/sig-simulation

Thank you for your cooperation in improving our repositories and supporting our community.

**Comment by vincent6767** [comment]
I can take this one unless you have started, @tonybalandiuk . Here is the outline I suggest
1. Overview SIG. The same as [SIG charter](https://github.com/o3de/sig-release/blob/main/governance/SIG%20Release%20Charter.md#overview-of-sig)
2. Goals. The same as [SIG charter](https://github.com/o3de/sig-release/blob/main/governance/SIG%20Release%20Charter.md#goals)
3. Responsibilities. The same as [Scope](https://github.com/o3de/sig-release/blob/main/governance/SIG%20Release%20Charter.md#scope) and [In-scope](https://github.com/o3de/sig-release/blob/main/governance/SIG%20Release%20Charter.md#in-scope) on the SIG charter.
4. How to contribute.
* Shares any feedback or idea to improve the O3DE release process
* Help drives addressing feedback or idea to improve the O3DE release process
6. How to engage with the SIG
* via Discord channel.
* via bi-weekly meeting.
* via GHI in the SIG release repo.

Thoughts? @tonybalandiuk

**Comment by vincent6767** [comment]
@aFinchy Wondering what will be the differences between the SIG charter and the readme after this issue is closed. To me, the content is very similar, to explain the outline I mentioned above.

**Comment by tonybalandiuk** [comment]
@vincent6767 please go ahead and take it. I have not yet started.

**Comment by vincent6767** [comment]
I'll take a look next week.

**Comment by vincent6767** [comment]
https://github.com/o3de/sig-release/pull/153
@tonybalandiuk @aFinchy Please review!
