### ISSUE TITLE
Joint TSC Meeting - March 28th, 2023

### ISSUE THREAD

**Issue by vincent6767** [o3de/sig-release#152]
What we did last month
1. Stabilization branch was created. The stabilization period ends on April 11th, 2023 PDT. Next milestone: Code freeze on major bugs, Versioned API reference generation, and release notes finalized by the docs team.
2. Decided o3de-extras as a canonical repo, which means we will start including it in the next release 23.05
3. SIG Docs community created the PR to make all SIG roadmaps more discoverable by creating a new roadmaps page and updating the contribute home page: https://discord.com/channels/805939474655346758/821692567355523152/1087850071816683570
4. Proposed to TSC on adding "Maintaining roadmap" responsibility on each SIG charter. Waiting for the response.

What we're going next month based on the roadmap: https://github.com/orgs/o3de/projects/29
1. Release considered stable to go live on May 3rd, 2023.
2. Complete all action items on [RFC "Maintaining Roadmap"](https://github.com/o3de/sig-release/issues/128).
3. Completes the [O3DE release process](https://github.com/o3de/sig-release/issues/134).

**Comment by tonybalandiuk** [comment]
posted above over at https://github.com/o3de/tsc/issues/74
