### ISSUE TITLE
[Pre Release] Ensure release Feature List is drafted and distributed

### ISSUE THREAD

**Issue by tonybalandiuk** [o3de/sig-release#155]
Ensure the Release SIG drafts the detailed Feature List, which describes the contents of the release. Provides this to release stakeholders, as needed (for example, the O3DE marketing-committee may need this in advance of the release as input into marketing requirements).

1. Publish an initial feature list file to https://github.com/o3de/sig-release/blob/main/releases/23.05.0/23050%20feature%20list.md
2. Notify sig-all, sig-release asking the community to contribute
3. Contact Royal to have him reach out to partners to contribute
4. Review closed issues to see if anything else should be added.

- Related Task: 
- Predecessor Task: 
- Successor Task: 

Discord: [#sig-release](https://discord.gg/ne59x9bc)
Release SIG meetings: [O3DE Calendar](https://lists.o3de.org/g/o3de-calendar/calendar)
Release SIG meeting agendas: [GHI](https://github.com/o3de/sig-release/issues)

**Comment by tonybalandiuk** [comment]
started work on this

**Comment by tonybalandiuk** [comment]
https://github.com/o3de/sig-release/issues/133

**Comment by tonybalandiuk** [comment]
Posted in SIG-All, SIG-Release, Marketing, and contacted Royal via Discord.
Not sure if I will get to "Review closed issues to see if anything else should be added." - it's an ideal thing to do and it's fairly costly to manually review closed issues.

**Comment by tonybalandiuk** [comment]
Still need to develop the "theme" for the release. Discussed with @Naomi-Wash on 4/18 and agreed I will work on the theme this week.

**Comment by Naomi-Wash** [comment]
Feature highlights identified by the outreach committee (based on Release Notes) and SIG-Network:

- 3D user workflow experience: Material Canvas, Shader Library updates
- Usability: new asset browser
- Additional VR/XR support
- Physics & animations improvements
- Terrain system enhancements
- SIG/Network's main contribution to the 2305 is the whole new MultiplayerSample game which has driven huge improvements in O3DE from network performance to rendering. The sample should be highlighted for the release as its visually really interesting, shows some of the possibilities of O3DE etc but its buried in the feature matrix, as thats more functional.

**Comment by tonybalandiuk** [comment]
I agree with those @Naomi-Wash . I took that list and re-formatted some of those under main headings, and added some details. Currently in this PR https://github.com/o3de/sig-release/pull/179
I don't really have a "theme" - hopefully marketing can help with that.

**Comment by tonybalandiuk** [comment]
done.
