### ISSUE TITLE
[Pre Release] O3DE 23.05.0 Release: Ensure final release notes are documented, and a PR is created

### ISSUE THREAD

**Issue by vincent6767** [o3de/sig-release#166]

**Comment by chanmosq** [comment]
Here's the timeline for Release Notes (and Feature Grid)
- April 19, 2023 - Release Notes: A PR will be created by this date. A reviewer from sig-docs-community and sig-release are needed to approve the PR.  We will continue to accept changes until April 26.
- April 26, 2023 - The final date to accept changes to the Release Notes.
- April 27, 2023 - The PR should be merged. _Note: This is a few days before release day, May 3, which provides time in case it's needed._

**Comment by chanmosq** [comment]
https://deploy-preview-2394--o3deorg.netlify.app/docs/release-notes/2305-0-release-notes/
