### ISSUE TITLE
[Pre Release] Decides which o3de-extras gems are going to be part of the 23.05 release

### ISSUE THREAD

**Issue by vincent6767** [o3de/sig-release#172]
Criteria to be part of the 23.05 release
1. Gems are tested and confirmed by the owner SIGs or community members.

Gems we have identified so far
1. XR gems (2)
    1. Confirmed by @byrcolin . Conversation [here](https://discord.com/channels/805939474655346758/1095140837383479357/1095428851171070155).
2. Multiplay Template. 
    1. Confirmed by @lmbr-pip . Conversation [here](https://discord.com/channels/805939474655346758/1095140837383479357/1096111275622285412)
3. AzQtComponentsForPython gem. 
    1. 4/24 @AMZN-alexpete verified it compiles OK
4. ROS2 Gem and ROSConDemo confirmed by @adamdbrw 

Notes
1. Conversation can be read here: https://discord.com/channels/805939474655346758/1095140837383479357/1095146336438984814

**Comment by vincent6767** [comment]
@Naomi-Wash @tonybalandiuk FYI I add another pre-release task for 23.05

**Comment by tonybalandiuk** [comment]
@AMZN-alexpete @Ulrick28 @cgalvan  FYI - this is where we will document the decision on the o3de-extras gem and exactly which content will be merged under #161

**Comment by Ulrick28** [comment]
Robotec.ai is maintaining the ROSCon demo and the ROS2 gems. I'll ping them concerning verification.

**Comment by AMZN-alexpete** [comment]
I also verified I could import `azqtpyside` in the Editor's Python console window, create an instance of `azqtpyside.AzQtComponents.FileDialog` and run the `GetSaveFileName()` function which opened the correct dialog and returned the correct file result.

**Comment by adamdbrw** [comment]
ROS 2 Gem should also be a part of the release, we have been using it with O3DE stabilization for a while and will run test campaign this week for the release.

We will also stabilize ROSConDemo and make it work with O3DE & ROS 2 releases. This is also planned for this week (targeting Thursday EOD or Friday latest)

**Comment by vincent6767** [comment]
Thanks @adamdbrw I'll update the issue to include the ROS 2 Gem as part of the 23.05 release.
CC: @tonybalandiuk
