### ISSUE TITLE
Joint TSC Meeting - May 30th, 2023

### ISSUE THREAD

**Issue by vincent6767** [o3de/sig-release#191]
What we did last month
1. Released 23.05 in collaboration with other SIGs and gathered release feedback from the team.

What we're going next month based on the roadmap: https://github.com/orgs/o3de/projects/29
1. Do the 23.05 release retrospective, and decide on the next item of improvement.
2. Together with TSC to decide whether we would want to mention the roadmap maintenance are one of the SIG responsibilities on the SIG charter. This is the issue that tracks this discussion: https://github.com/o3de/sig-release/issues/146
3. Start a discussion about the next release date.

Proposed Agenda
1. To discuss features grid maintenance effort and make sure everyone agrees that it's important to be maintained.
   1. Challenges
       1. The features grid is one of the release deliverables. Updating the grid generally involves two steps. First, SIG has to manually update each of the sections that it owns, along with other release deliverables. Second, the SIG Community-and-docs converts the grid's JSON file into a document format (I believe it is a markdown). You can see what it looks like on the docs page [here](https://www.o3de.org/docs/release-notes/archive/22-05-0/feature-state/).
       2. Few challenges faced in the past two releases
           1. SIG needs to spend time manually maintaining the grid in addition to its other responsibilities. It also requires two approvals, which makes it even slower.
           2. The Release manager needs to persistently remind SIGs to update the grid as the task is often buried by other higher-priority tasks.
           3. It takes time for SIG docs-and-community to convert the JSON into the markdown format.
     2. Questions to be discussed
        1. As you saw above, it takes effort to maintain the feature grid. However, the SIG release does not have visibility of how helpful the feature grid is to the community. Given that condition, SIG release would like to open a discussion with TSC and other SIGs to make sure the feature grid is still important to be maintained and everyone agrees that it is part of the O3DE release deliverable.
5. Decides the next steps for mentioning the roadmap maintenance responsibility in the SIG charter (or general guidelines).

**Comment by vincent6767** [comment]
@tonybalandiuk Feel free to edit the issue above in case there are updates that I miss.

**Comment by vincent6767** [comment]
re: Feature grid.
@tonybalandiuk TSC and SIGs who attended today's TSC call are in agreement to keep maintaining the feature grid as this is helpful for people who would like to know the current condition of the engine.

**Comment by chanmosq** [comment]
@vincent6767 Yes, I do use that button to convert into Markdown. However, it's not in the perfect format, so it requires manual cleanup as well

**Comment by vincent6767** [comment]
Thanks for confirming. So that's part of the improvement for the features grid.
