### ISSUE TITLE
Proposed SIG-Release meeting agenda for 2023-06-06

### ISSUE THREAD

**Issue by vincent6767** [o3de/sig-release#193]
## Meeting Details

- **Date/Time:** June 6th, 2023 @ 5:00pm UTC / 10:00am PDT
- **Location:** [Discord SIG-Release Voice Room](https://discord.gg/Z2bzwCRJEz)
- **Moderator:**: @tonybalandiuk 
- **Note Taker** : @vincent6767

The [SIG-Release Meetings](https://github.com/o3de/sig-release/tree/main/meetings) repo contains the past historical calls, including a link to the agenda, recording, notes, and resources.

## SIG Updates
- Feature grid will still be part of the O3DE release deliverable as decided in the Joint TSC meeting. You can read the note [here](https://github.com/o3de/sig-release/issues/191#issuecomment-1568709344).

## Meeting Agenda
1. On the Join TSC meeting on May 30th, 2023, Royal proposes to have the retrospective session together with TSC and other SIG members during one of the office hours. The agenda for today is to decide the following action steps, whether to hold the session with other members or do it ourselves.
2. Decides when we are going to decide the next release date.

**Discuss agenda from proposed topics**

**Comment by tonybalandiuk** [comment]
Proposed Topic
Next SIG-Release Election

**Comment by vincent6767** [comment]
https://github.com/o3de/sig-release/pull/194
