### ISSUE TITLE
RFC for Release charter

### ISSUE THREAD

**Issue by Ulrick28** [o3de/sig-release#2]
Please read and provide feedback on our charter in this thread:

**SIG <Template> Charter**

This charter adheres to the Roles and Organization Management specified in <sig-governance>.
 Team information may be found in the <readme.md>

**Overview of SIG**

This group is the coordinating group that works with all sigs to collect and produce a release package in a cadence with a standard process. This sig is created with chairs and maintainers from each horizontal SIG as well as dedicated members.

Two concise lines explaining what this SIG does with bullet points of the major responsibilities

- Responsibility 1

**Goals**
Make sure releases are 

Manage schedule of releases and cadence
Determine release naming convention

- Major goals that SIG seeks to generally achieve

**Scope**
Define process and explanation of what an actual release is and what is expected
Manage and define strategies for finalzing and collecting merge requests to branch
Define and iterate on release process and github workflow
Define Branching strategy and pre-release schedule 
Define freeze resolution strategies
Define late breaking changes strategies
Define packaging and methods per platform for assets.

- Generalized overall scope of work

**In scope**

Responsible for confirming final state of release for any blocking issues.
Define process for triage of issues through QA/Testing, SIG bug reporting, and resolution for elements in release schedule.
Responsible for merging and producing post release hotfixes and patches

- Items that are the core responsibilities of SIG

**Cross-cutting Processes**

Work with QA/Testing to define and maintain minimum quality of expectations for point releases are.

Coordinate and communicate the schedule release dates and market timing, documentation and release notes publishing to docs and Governing Board (public communication)

Responsibility to define and monitor the process to determine features to be added into future release schedules along with the TSC.

Define process to resolve schedule conflicts due to issues.

Coordinate with SIGs on post-release hotfixes and patches, but not responsible for performing fixes.

Define process for coordination with out of schedule or schedule challenged dependencies across SIG feature release items.

- Items that span or require other SIGs or groups and how it relates to this SIG’s responsibilities

**Out of Scope**
Not responsible feature development schedules and branch management of features
Not responsible for triaging or fixing bugs
Not responsible for end user support
Not responsible for quality or capability of any specific feature
Not responsible for metrics, crash and post-release reporting, but will consult with documentation and sigs for coordination of metrics collection.
Not responsible for product feature decisions for releases, but may be consulted along with TSC, GB and SIGs.

- Items that are optional or are not the responsibility of this SIG.

**SIG Links and lists:**

- Joining this SIG
- Slack/Discord
- Mailing list
- Issues/PRs
- Meeting agenda & Notes

**Roles and Organization Management**

SIG Docs adheres to the standards for roles and organization management as specified by <sig-governance>. This SIG opts in to updates and modifications to <sig-governance>

**Individual Contributors**
All features must be submitted with a specific release value before being accepted.

Additional information not found in the sig-governance related to contributors.

**Maintainers**

Additional information not found in the sig-governance related to contributors

**Additional responsibilities of Chairs**

Additional information not found in the sig-governance related to SIG Chairs

**Subproject Creation**

Additional information not found in the sig-governance related to subproject creation

**Deviations from sig-governance**

Explicit Deviations from the sig-governance

**Comment by tonybalandiuk** [comment]
done here https://github.com/o3de/sig-release/blob/main/governance/SIG%20Release%20Charter.md
