### ISSUE TITLE
[Pre Release] O3DE 23.10.0 Release: Ensure installers are uploaded to S3 and the engine is set to 2.1.0

### ISSUE THREAD

**Issue by Naomi-Wash** [o3de/sig-release#226]

**Comment by amzn-mike** [comment]
@Naomi-Wash I'm assuming this was meant for @amzn-changml?

**Comment by Naomi-Wash** [comment]
It sure was,sorry @amzn-mike .

**Comment by Naomi-Wash** [comment]
Reference engine set to 2.1.0 background here: https://github.com/o3de/o3de/issues/16800
