### ISSUE TITLE
[Pre Release] O3DE 23.10.0 Release: Ensure PR is created for bumping the version number in the Linux install instructions

### ISSUE THREAD

**Issue by Naomi-Wash** [o3de/sig-release#231]

**Comment by RoddieKieley** [comment]
This should be covered by draft o3de.org PR
- [Updated version information from 23.05 to 23.10. #2477](https://github.com/o3de/o3de.org/pull/2477)
as per the [diff](https://github.com/o3de/o3de.org/pull/2477/files#diff-1b0806d980cf573f1139e3f9df4aab423aecd4671fe140c1b8feffb2e26db4ad)

Likely needs review to ensure the final installer name is correct at the very least.
