### ISSUE TITLE
[Pre Release] O3DE 23.10.0 Release: Ensure PR is created for applying the generated API reference to the docs site

### ISSUE THREAD

**Issue by Naomi-Wash** [o3de/sig-release#241]

**Comment by RoddieKieley** [comment]
See draft PR  [23.10 regenerated api reference #2478](https://github.com/o3de/o3de.org/pull/2478) the summary for which indicates at the moment:

- Regenerated o3de framework apis from o3de stabilization/2310 branch.
- Regenerated o3de gem apis from o3de stabilization/2310 branch.
- Regenerated o3de-extras gem apis from o3de-extras stabilization/2310 branch.
