### ISSUE TITLE
Proposed SIG-Release meeting agenda for August-29-23 *DRAFT*

### ISSUE THREAD

**Issue by RoddieKieley** [o3de/sig-release#244]
## Meeting Details

- **Date/Time:** August 29th, 2023 @ 5:00pm UTC / 10:00pm ET
- **Location:** [Discord SIG-Release Voice Room](https://discord.gg/Z2bzwCRJEz)
- **Moderator:** TBD
- **Note Taker** TBD

The [SIG-Release Meetings](https://github.com/o3de/sig-release/tree/main/meetings) repo contains the history past calls, including a link to the agenda, recording, notes, and resources.

## SIG Updates

- TBD

## Meeting Agenda

- 23.10.0 Release Planning and execution

**Comment by Ulrick28** [comment]
Would like to discuss the features being added to the release and themes.

Improving the ability for users to get started
        AWS AMI 
        Snap Packaging Improvements
        No Compile Project
Improving workflows and tools
        Document Property Editor 
        Customizable Render Pipeline
        ScriptCanvas Compact Nodes
        Gazebo Importing
        Nested Prefabs
        Fixes and compile time improvements.
Improving the ability for customers to publish and share
        Remote Repo Automation
        Project Exporting

**Comment by Naomi-Wash** [comment]
Meeting Recording: https://drive.google.com/file/d/1bKjQl69I8vIzNCkT3iLZUXbx3ZfdLk5S/view?usp=drive_link
