### ISSUE TITLE
[Pre Release] Prepare Build - 2 Days Before Release [Monday - Oct. 7]

### ISSUE THREAD

**Issue by Naomi-Wash** [o3de/sig-release#269]
We prepare the build two days before in order to save time in the release day.

- All pre-work needs to be completed on Monday, Oct. 7.
- Friday, September 27 will be used for verification only.

# Merge of Stabilization to Main

**Execute the following steps:**

- [ ] [@Ulrick28] Confirm the following pre-requisites are complete:
- [ ]  [@nick-l-o3de] https://github.com/o3de/sig-release/issues/285
- [ ] [@Ulrick28] https://github.com/o3de/sig-release/issues/286

# Installers
[Person]Confirm the following pre-requisites are complete (@amzn-changml @Ulrick28):
- [x] https://github.com/o3de/sig-release/issues/292

**Comment by Ulrick28** [comment]
Fedora will come in after the release, hopefully before ROSCon

**Comment by Naomi-Wash** [comment]
- [ ] @amzn-changml Create new stabilization builds after splash page has been added. @Ulrick28 will ping Mike once it has been submitted.
- [ ] @amzn-changml Remove snap packages from the binaries page. 
- [ ] @Ulrick28 Post on Discord about Snap being removed.

**Comment by amzn-changml** [comment]
The snap package changes and release binaries are now available in the preview page:

Windows: https://d2o572vhva5jdo.cloudfront.net/download/windows.html
Linux: https://d2o572vhva5jdo.cloudfront.net/download/linux.html
