### ISSUE TITLE
Proposed Sig-Release Meeting Agenda Topic: RTE Point Release early January

### ISSUE THREAD

**Issue by Ulrick28** [o3de/sig-release#27]
We have identified substantial workflow improvements, via the RTE program, that we would like to include in a point release in January. These improvements will not be stabilized in time for the 11/30 release, however, they add enough value that we feel a point release may be justified. I propose we discuss and then vote on supporting an early January release. This vote does not mean we will or will not have a release, it is primarily whether or not sig-release supports a potential release in January. We will take the outcome of this vote to the Steering Committee for a final yes/no decision. 

RTE refers to the Rev The Engine initiative to improve common workflows. More detailed information can be found here https://github.com/o3de/sig-ui-ux/tree/main/rev-the-engine

**Comment by yuyihsu** [comment]
Here's the Rev the Engine goals for 2021- https://github.com/o3de/sig-ui-ux/blob/main/rev-the-engine/2021Goal.md

**Comment by tonybalandiuk** [comment]
Update on this: We spoke with TSC on 12/7 and they have no concerns.  
We are planning a point release tentative for Jan 13, 2022. 
We chose this date based on the following:
Anticipated code freeze on  the Stabilization/2111 branch on 12/17 (date RTE issues are planned to be resolved).
Avoid bleeding into weekends
Allow everyone a week to recover from the holiday breaks
Give time for QA and address any issues after the break (Note that December 20th - January 2nd are very slow for contributors as most people are out during this time)
