### ISSUE TITLE
[Planning] Ensure Docs-Community SIG requirements are identified

### ISSUE THREAD

**Issue by Naomi-Wash** [o3de/sig-release#276]
Work with the Docs-Community SIG to define requirements, and determine if any of the requirements will block the release if not completed prior to the release.

These requirements could include, for example,

- Generate the C++ API reference for O3DE’s source code.
- Finalize release notes.
- Update Documentation versioning.
- Update the website to display the correct version number.

**A complete description of requirements can be found in the [Docs Release Process Runbook](https://github.com/o3de/sig-release/blob/main/releases/Process/Docs%20Release%20Process.md#docs-release-process-runbook).**
- Successor Task: (placeholder - confirm all launch blocking ...)
- Successor Task: (placeholder - confirm all non-launch blocking ...)

Discord: [#sig-docs-community](https://discord.gg/FxmvF5x8)
SIG Docs-Community meetings: [O3DE Calendar](https://lists.o3de.org/g/o3de-calendar/calendar)
SIG Docs-Community agendas: [GHI](https://github.com/o3de/community/issues)

**Comment by Naomi-Wash** [comment]
Include:
- No Code Project documentation
- Robotec.ai

**Comment by ShaunaGordon** [comment]
@Naomi-Wash I think @jhanca-robotecai has been taking point on the Robotec.ai stuff.

I don't know anything about the No Code Project documentation, though. Do you know who worked on that feature?

**Comment by ShaunaGordon** [comment]
Task list:

- [ ] Create stabilization branch
  - [ ] Fix merge conflicts in stabilization branch
- [ ] Update version dropdown in stabilization
  - [ ] Backport version dropdown update to previous versions
- [ ] Update website to reflect new version
  - [ ] Update download link
- [ ] Generate C++ API docs
  - [ ] Merge API docs update into stabilization
- [ ] Finalize release notes
  - [ ] Create PR for release notes

**Comment by Naomi-Wash** [comment]
Thanks @ShaunaGordon. You are correct about Robotec.ai owning the Ros elements, and @nick-l-o3de is on the No Code. (cc @Ulrick28).

**Comment by Naomi-Wash** [comment]
@Naomi-Wash Pull Shauna's template into future release projects.
