### ISSUE TITLE
Proposed release naming guidance from Marketing Committee

### ISSUE THREAD

**Issue by FiniteStateGit** [o3de/sig-release#39]
The Marketing Committee submits the following message for Sig-Release's review:

Release Naming Guidance

The use of 'major' and 'point' to describe the type of release is optional, but approved, for shorthand/non-technical descriptions.
> Example: ...the last major release...
> Example: ...an upcoming point release...

A major release follows the format: 
`<Last two digits of year>.<Last two digits of month>.<Versioning digit = 0>`
A point release re-uses the year and month of the previous major release and increments the versioning digit by one.
> Example: A major release in June 2025 would be named `25.06.0`
> Example: A point release in July 2025 would be named `25.06.1`
> Example: A second point release in January 2026 would be named `25.06.2`
> Example: A major release in January 2026 would be named `26.01.0`

A major release can be referred to in non-technical descriptions without the versioning digit.
> Example: `25.06`, in general, would refer to a major release from June 2025.

The marketing committee recommends that friendly names are not used for releases.

**Comment by Ulrick28** [comment]
Technical Steering Committee have given approval for this proposal, though would like SIG-Release to still vote on the topic.

**Comment by tonybalandiuk** [comment]
can we clarify what we mean by "friendly name" here?

**Comment by tonybalandiuk** [comment]
this has been approved/accepted. Closing it now although it has been accepted for the past few releases.
