### ISSUE TITLE
Propose Sig-Release Meeting Agenda Topic: RTE Point Release Retrospective

### ISSUE THREAD

**Issue by forhalle** [o3de/sig-release#41]
We are looking for feedback on the execution of the 21.11.2 Point Release. For example:

- Were the mechanisms and tools we implemented to track the release (for example, the [Point Release Project Board](https://github.com/o3de/o3de/projects/8), and the [Exception Request Project Board](https://github.com/o3de/o3de/projects/7)) sufficient in keeping everyone informed?
- Were we transparent enough in terms of the work required and the status of execution?
- Do we feel the point release process is clear enough to support non-Amazon contributors in running this process? If not, by what means do we need to bolster the process?
- Any other feedback?

**Comment by AMZN-daimini** [comment]
> We are looking for feedback on the execution of the 21.1.1 Point Release.

2111.2? :)

**Comment by forhalle** [comment]
Oops - thanks for the correction!

**Comment by forhalle** [comment]
Notes:

Q1: Were the mechanisms and tools we implemented to track the release (for example, the Point Release Project Board, and the Exception Request Project Board) sufficient in keeping everyone informed?
A1: Both tools were useful for tracking and keeping everyone informed. We should evangelize the Exception Request Project Board more. 
(captured as action below) AMZN Halle F will create a GHI issue to finalize and evangelize the Exception Request process and project board.
Q2: Were we transparent enough in terms of the work required and the status of execution?
A2: We may want to make it more obvious what documentation changes are included in a release. This is also a way to recognize the doc work.
(captured as action below) AMZN Stephen T to get feedback from SIG Docs Community regarding if we should make documentation changes more apparent in release notes.
Q3: Do we feel the point release process is clear enough to support non-Amazon contributors in running this process? If not, by what means do we need to bolster the process?
A3: Although we have a good start based on the current mechanisms and tools, the most difficult part will be for for Amazonians to break their reliance on internal processes and tools. This is surmountable, and we can use Finchy to drive perspective (since she has recently joined Amazon and carries with her the contributor perspective)
(captured as action below) AMZN Halle F will send JT the project runbook
