### ISSUE TITLE
Retro for O3DE Release 22.05.0 (Feedback due by May 26, 2022)

### ISSUE THREAD

**Issue by tonybalandiuk** [o3de/sig-release#59]
This issue will serve to collect feedback on the O3DE 22.05.0 release.

The entire O3DE community is encouraged to participate here by commenting on this issue so we can improve our releases. To make your comment useful, please start out your comment with one of the following phrases:
"Something that went well..." 
"Something that didn't go well..."
"Something that we should change..."

**Next Steps**

- [x]  Solicit Feedback under this issue. All feedback due by May 26, 2022
- [x]  (optional) Depending on the feedback received, set up a specific public meeting to have further discussion about the 21.11 release. 6/6 DECIDED against a separate meeting, see comment below
- [x] For all "Things we want to change" create issues as needed or note how this will get addressed.
- [x] Post a summary to the SIG-Release channel

### Retro is Below this line 
_The below is an aggregate of all of the comments posted to this issue_

**Things that went well**
* I can actually run the engine on my Intel i5 iris gpu laptop as before it just failed to start not even producing a log.
* Have not had time to do any testing apart from start-up and create a level.
* I was able to download the engine and install on my personal machine (which had 21.11 installed) and it went super-smooth with no issues (while I did have issues with a similar scenario before).
* Stabilization went quite well and changes flowing back to development didn't cause issues.
* Stabilization process and not rushing features in protected the release from destabilization, leading to more stable and less stressful release.
* Several blogs and videos timed around the release.
* Positive perception of the release 'it just works'
* Having an LF side Marketing and Community manager improved communication, particularly when compared to the 21.11.1 release.
* Regular updates on progress, schedule
* Front-loaded release note work, much smoother getting info to release team
* Integrations from stabilization to development largely went smoothly (would be great to try and include more external contributors for this in future too!)
* Triage / escalation process went well.
* Clear expectations set around quality bar for getting into stabilization.
* Docs team very responsive on docs updates for mainline.

**Things that didn't go well**
* Branding inconsistencies between Editor and Websites. We still need to figure out a good strategy to keep the branding consistent across all parts of the project.
* Similarly, there were inconsistencies in referencing the version number in the installer (22.5.0.0), editor splash screen (2205.0) and website (Stable 22.05).
* Branding came in at the last minute, leading to large, potentially destabilizing changes after stabilization lockdown
* Confusion around what logos needed to be changed where and with what version of the logo
* Communication about impending release was not far enough ahead, leading to questions from sig members who were surprised by the upcoming release
* Need a more consistent release notes process, as the notes came in at the last minute
* Marketing plan came in late, making it difficult for the release sig to react and/or take advantage of the plan
* Project Manager feature not working with VS 2022 out of the gate
* 11th hour issues - would be great to test these workflows earlier and more often if possible (as well as have automation to detect issues sooner rather than later).
* DCO issues for merges are still a problem, would be great to try and eliminate/fix these sooner.
* Lack of cross SIG communication about blocker/critical issues. Some issues were not raised/evaluated to see if they should be considered must fixes for release.
* Lots of scrambling around logo updates
* Lack of automation in many areas (hello asset pipeline, networking) means we are still doing expensive manual regressions.
* No clear ownership of migrating old release notes (had to go back and do a lot of a digging to see if issue x was still happening).
* No clear versioning information on docs site.

**Things we should change**
* Make the registry folder with the o3de_manifest.json selectable even if its a cmake option. I understand it is not as straightforward as some might think but have seen this requested by a few people.
    * This is related to bug https://github.com/o3de/o3de/issues/2078 - added a comment there.
* Maybe make it easier overall to handle multiple engines.
    *  This is a current feature request: https://github.com/o3de/o3de/issues/3536
* Determine a release manager earlier (at least 90 days ahead of release)  
    * noted as a todo under https://github.com/o3de/sig-release/issues/64
* Determine release date earlier (at least 90 days ahead of release)
    * as of 6/14 the proposed release date has been posted under https://github.com/o3de/sig-release/issues/64
* Document release notes process and timeline
    * noted as a todo under https://github.com/o3de/sig-release/issues/64
* Coordinate with Marketing Sig earlier. Set deadlines!
    *  noted as a todo under https://github.com/o3de/sig-release/issues/64
* Clearer notification of timeline for release builds. Set date early so we can plan around disruption. Set clear dates up front with SIGs around testing.
    * noted as a todo under https://github.com/o3de/sig-release/issues/64
* More regression / adhoc testing early in process. Mentioned to sig-testing in Discord. https://discord.com/channels/805939474655346758/816043958341861376/988934730516955226
* Release notes should mostly be driven off issues, but issues can change/reopen/close post release. Not sure if we still have clear process.
    * noted as a todo under https://github.com/o3de/sig-release/issues/64
* Weekly SIG triage cadence does not gel with limited window for release builds. May need SIG of SIGs daily triage or clearer mechanisms for raising and escalating issues. Waiting a week for a SIG to respond on a critical which should be launching blocking seems risky.
    * noted as a todo under https://github.com/o3de/sig-release/issues/64

**Comment by GraphiteSIX** [comment]
Things that went well: 
I can actually run the engine on my Intel i5 iris gpu laptop as before it just failed to start not even producing a log.
Have not had time to do any testing apart from start-up and create a level.

Things we should change:
Make the registry folder with the o3de_manifest.json selectable even if its a cmake option.
I understand it is not as straightforward as some might think but have seen this requested by a few people.
Maybe make it easier overall to handle multiple engines.

**Comment by Ulrick28** [comment]
**Things that went well**
- Stabilization process and not rushing features in protected the release from destabilization, leading to a stabler and less stressful release.
- Several blogs and videos timed around the release.
- Positive perception of the release 'it just works'
- Having an LF side Marketing and Community manager improved communication, particularly when compared to the 21.11.1 release.

**Things that didn't go well**
- Branding came in at the last minute, leading to large, potentially destabilizing changes after stabilization lockdown
- Confusion around what logos needed to be changed where and with what version of the logo
- Communication about impending release was not far enough ahead, leading to questions from sig members who were surprised by the upcoming release
- Need a more consistent release notes process, as the notes came in at the last minute
- Marketing plan came in late, making it difficult for the release sig to react and/or take advantage of the plan
- Project Manager feature not working with VS 2022 out of the gate

**Things we should change**
- Determine a release manager earlier (at least 90 days ahead of release)
- Determine release date earlier (at least 90 days ahead of release)
- Document release notes process and timeline
- Coordinate with Marketing Sig earlier. Set deadlines!

**Comment by hultonha** [comment]
#### Things that went well

- Regular updates on progress, schedule
- Front-loaded release note work, much smoother getting info to release team
- Integrations from stabilization to development largely went smoothly (would be great to try and include more external contributors for this in future too!)

#### Things that didn't go well

- 11th hour issues - would be great to test these workflows earlier and more often if possible (as well as have automation to detect issues sooner rather than later).
- DCO issues for merges are still a problem, would be great to try and eliminate/fix these sooner.

(_I'll likely edit this with more things I remember until the 26th_ 🙂)

**Comment by lmbr-pip** [comment]
Things that went well
* Triage / escalation process went well.
* Clear expectations set around quality bar for getting into stabilization.
* Docs team very responsive on docs updates for mainline.

Things that didn't go well
* Lack of cross SIG communication about blocker/critical issues. Some issues were not raised/evaluated to see if they should be considered must fixes for release. 
* Lots of scrambling around logo updates
* Lack of automation in many areas (hello asset pipeline, networking) means we are still doing expensive manual regressions.
* No clear ownership of migrating old release notes (had to go back and do a lot of a digging to see if issue x was still happening).
* No clear versioning information on docs site.

Things we should change
* Clearer notification of timeline for release builds. Set date early so we can plan around disruption. Set clear dates up front with SIGs around testing.
* More regression / adhoc testing early in process.
* Release notes should mostly be driven off issues, but issues can change/reopen/close post release. Not sure if we still have clear process.
* Weekly SIG triage cadence does not gell with limited window for release builds. May need SIG of SIGs daily triage or clearer mechanisms for raising and escalating issues. Waiting a week for a SIG to respond on a critical which should be launching blocking seems risky.

**Comment by tonybalandiuk** [comment]
Based on the feedback received under this retro issue , as the release manager I am NOT inclined to have a separate "retro" meeting to further discuss the release. All of the feedback here seems to make sense and nothing jumps out as "needing to talk about right now". Under the specific action items that come out of the retro, there will need to be some discussion, but nothing that I believe needs to happen right now.

**Comment by tonybalandiuk** [comment]
@GraphiteSIX  
> Things we should change: Make the registry folder with the o3de_manifest.json selectable even if its a cmake option.

To make sure I understand, would your concern be addressed by this bug? -> https://github.com/o3de/o3de/issues/2078

**Comment by tonybalandiuk** [comment]
I noted 5 of these as "TODOs" for the next release - things I think the release manager will need to take into account. When I document the release process overall, I will make sure to include these as well.

**Comment by tonybalandiuk** [comment]
keeping this open until we discuss in the next SIG-Release meeting on 6/21

**Comment by tonybalandiuk** [comment]
closing. Discussed in our sig-release meeting today. I had one todo coming out of the meeting to address the "more regression / adhoc testing" comment that was in the "Things we should change". I reached out to sig-testing chairs in Discord.
