### ISSUE TITLE
Sig-Release 2022 Roadmap

### ISSUE THREAD

**Issue by tonybalandiuk** [o3de/sig-release#62]
This issue will track any Roadmap items that SIG-Release will contribute to the O3DE Roadmap for 2022.

* Date TBD Formalize the release process. This will be done in advance of the 22.10.0 release.
* Oct 13, 2022 O3DE 22.10.0 Release https://github.com/o3de/sig-release/issues/64

Please comment under this issue with any other roadmap items for sig-release

**Comment by NiklasHenricson** [comment]
Hello,

Back in Nov 2021 I asked if it would be possible to re-add LY's old infinite ocean/water gem back in O3DE.

The thread is here,

https://github.com/o3de/sig-graphics-audio/issues/22

I haven't heard much since, even though we had a meeting about this. Could we please get some traction on that topic?


Thank you in advance,
Nik

**Comment by tonybalandiuk** [comment]
Another roadmap item: formalizing the release process

**Comment by tonybalandiuk** [comment]
> Back in Nov 2021 I asked if it would be possible to re-add LY's old infinite ocean/water gem back in O3DE.
> 
> The thread is here,
> 
> [o3de/sig-graphics-audio#22](https://github.com/o3de/sig-graphics-audio/issues/22)
> ...

@NiklasHenricson  I have raised this concern to the sig over in Discord https://discord.com/channels/805939474655346758/816043793576886273/986341408560513054

**Comment by tonybalandiuk** [comment]
This was an action item from the 10/25 sig-release meeting. Turns out we already have this task to create a roadmap, so let's re-use this existing task @vincent6767  FYI

**Comment by vincent6767** [comment]
Should we close this out as we have our roadmap already? @tonybalandiuk

**Comment by vincent6767** [comment]
I'll close this as we have the roadmap already: https://github.com/orgs/o3de/projects/29
