### ISSUE TITLE
O3DE Release 22.10.0 Key Information

### ISSUE THREAD

**Issue by tonybalandiuk** [o3de/sig-release#64]
This issue is a single destination for all things related to the O3DE 22.10.0 Release. This issue will be updated as information changes. We will use this issue to surface questions and answer them so the entire community is aware of what to expect for the 22.10.0 release.

**O3DE 22.10.0 About this Release**
O3DE 22.10.0 will be the second major release of O3DE in 2022. The previous release was the 22.05.0 major release (May 13, 2022). The release will contain all of the features in the dev branch as of August 29, 2022 12:00 Pacific time. This release is intended to coincide with O3DE's Annual  [O3DCon](https://events.linuxfoundation.org/o3dcon/) October 18-19, 2022.

**Release Managers**
Release Manager: @tonybalandiuk (Discord @Tony B [Amazon]#7273)
Co-Release Manager:  @vincent6767 (Discord @vincentvinvent )

**Release Project Board**
https://github.com/o3de/o3de/projects/18

**Feature List**
https://github.com/o3de/sig-release/blob/main/releases/22.10.0/22100%20feature%20list.md

**Release Notes**
Coming September 2022

**Stabilization Branch**
Coming August 29. 2022

**Stabilization Bug Reporting**
In the stabilization branch, any bugs found should get the "Release/2210" milestone applied. 

**Bug Tracking**
O3DE main repo - Bugs are being tracked with the [Release/2210 Milestone.](https://github.com/o3de/o3de/milestone/11)
Atom Sample Viewer repo - TBD

**Release Schedule with Exception Process for Submitting Code to the Stabilization Branch**
As documented in the below table, submissions to the stabilization branch will be subject to an Exception Process, described [here](https://github.com/o3de/o3de/projects?type=classic) in the description for project "stabilization/2210 - Exception Requests"

Date | Description | Bug Fixes  Allowed in Stabilization Branch| New Features Allowed in Stabilization Branch
-- | --|--|--
Jul 1, 2022| Feedback period closed. No SIGs raised any concerns with release schedule | N/A | N/A
Jul 7, 2022| Marketing committee confirmed ok with proposed release schedule | N/A | N/A
Jul 12, 2022|Release managers posted, empty project board set up.| N/A| N/A
Aug 29, 2022 10am Pacific | Stabilization Branch created. |  N/A | N/A
Aug 30, 2022 | (Docs) Stabilization branch created | N/A | N/A
Aug 29 through Sep 26, 2022 | Stabilization Period | Yes | Yes via, exception process.
Sep 27, 2022 | Code Freeze on Major Bugs and below| Beginning this date, only Blocker and Critical bugs are allowed without the exception process. | No
Sep 30| (Docs) Versioned API reference generation | N/A | N/A
Sep 30, 2022 | (Docs) Release Notes Finalized (features + known issues) | N/A | N/A
Sep 30, 2022 | Code Freeze on Critical Bugs and below | Beginning this date, only Blocker bugs are allowed via the exception process.| No 
Sep 30 through Oct 5, 2022| QA Final Pass| Beginning this date, only Blocker bugs are allowed via the exception process, with risk of delaying the release.| No
Oct 5, 2022|Release considered "stable", all blocker/critical issues are resolved. | No| No
Oct 11, 2022|  Release tasks are done. Binaries posted, code merged, etc.| No | No
Oct 13, 2022  | 22.10.0 Release Marketing Announcement | No | No

**Comment by tonybalandiuk** [comment]
5 TODOs for the next release taken from the 22.05.0 Retro https://github.com/o3de/sig-release/issues/59

1. Determine a release manager earlier (at least 90 days ahead of release)  
2. Document release notes process and timeline. Release notes should mostly be driven off issues, but issues can change/reopen/close post release so we need a way to catch any changes.
3. Coordinate with Marketing Sig earlier. Set deadlines!
4. Clearer notification of timeline for release builds. Set date early so we can plan around disruption. Set clear dates up front with SIGs around testing.
5. Weekly SIG triage cadence does not gel with limited window for release builds. May need SIG of SIGs daily triage or clearer mechanisms for raising and escalating issues. Waiting a week for a SIG to respond on a critical which should be launching blocking seems risky.

**Comment by lmbr-pip** [comment]
Should we have any stated activities around feature identification (ie on x date, gather all features that may make release and provide to marketing?) Should we have a date for documentation lock for release?

**Comment by tonybalandiuk** [comment]
TODO - better description of "Stabilization"

**Comment by uoduckswtd1** [comment]
Timeline looks reasonable. We also need to establish when a list of key features/capabilities included in this release will be available & who is the contact for each -- we'll use this list to outline key marketing/advocacy deliverables, such as messaging, blogs, videos (including virtual demos), community chats (Twitch), etc.

**Comment by chanmosq** [comment]
The known issues will be collected here: https://github.com/o3de/o3de/discussions/12129

To clarify the docs timeline for the above calendar, 9/27 is the last day we are asking folks to submit their known issues. Finalizing the release notes can be from 9/27 to 10/5, coinciding with QA Final Pass.

**Comment by tonybalandiuk** [comment]
Schedule updated on 9/23. The main takeaway is that Blockers and Criticals (the bugs that are trying to resolve to stabilize the release) can be submitted through next Friday 9/30 without an exception. (Previously we were going to require exceptions starting 9/27).
