### ISSUE TITLE
SIG-Release Election Nominations 07/19 - 08/01 -- Elections 08/01 - 08/05

### ISSUE THREAD

**Issue by aFinchy** [o3de/sig-release#74]
## The chair / co-chair roles

The chair and co-chair serve equivalent roles in the governance of the SIG and are only differentiated by title in that the highest vote-getter is the chair and the second-highest is the co-chair. The chair and co-chair are expected to govern together in an effective way and split their responsibilities to make sure that the SIG operates smoothly and has the availability of a chairperson at any time.

Unless distinctly required, the term "chairperson" refers to either/both of the chair and co-chair. If a chair or co-chair is required to perform a specific responsibility for the SIG they will always be addressed by their official role title.

In particular, if both chairpersons would be unavailable during a period of time, the chair is considered to be an on-call position during this period. As the higher vote-getter they theoretically represent more of the community and should perform in that capacity under extenuating circumstances. This means that if there is an emergency requiring immediate action from the SIG, the chair will be called to perform a responsibility.

### Responsibilities

* Schedule and proctor regular SIG meetings on a cadence to be determined by the SIG.
* Serve as a source of authority (and ideally wisdom) with regards to O3DE SIG area of discipline. Chairpersons are the ultimate arbiters of many standards, processes, and practices.
* Participate in the SIG Discord channel and on the GitHub Discussion forums.
* Serve as a representative of the broader O3DE community to all other SIGs, partners, the governing board, and the Linux Foundation.
* Represent the SIG to O3DE partners, the governing board, and the Linux Foundation.
* Coordinate with partners and the Linux Foundation regarding official community events.
* Represent (or select/elect representatives) to maintain relationships with all other SIGs as well as the marketing committee.
* Serve as an arbiter in SIG-related disputes.
* Coordinate releases with SIG Release.
* Assist contributors in finding resources and setting up official project or task infrastructure monitored/conducted by the SIG.
* Long-term planning and strategy for the course of the SIG area of discipline for O3DE.
* Maintain a release roadmap for the O3DE SIG area of discipline.

*Additionally*, at this stage of the project, the SIG chairpersons are expected to act in the Maintainer role for review and merge purposes only, due to the lack of infrastructure and available reviewer/maintainer pool.

... And potentially more. Again, this is an early stage of the project and chair responsibilities have been determined more or less ad-hoc as new requirements and situations arise. In particular the community half of this SIG has been very lacking due to no infrastructural support, and a chairperson will ideally bring some of these skills.

## Nomination

Nomination may either be by a community member or self-nomination. A nominee may withdraw from the election at any time for any reason until the election starts on 08/01.

### Nomination requirements

The only other nomination requirement is that the nominee agrees to be able to perform their required duties and has the availability to do so, taking into account the fact that another chairperson will always be available as a point of contact.

### How to nominate

Nominations will be accepted for 2 weeks from 2022-07-19 12:00PM PT to 2022-08-01 12:00PM PT.
Nominate somebody (including yourself) by responding to this issue with:

* A statement that the nominee should be nominated for a chair position in the specific SIG holding its election. Nominees are required to provide a statement that they understand the responsibilities and requirements of the role, and promise to faithfully fulfill them and follow all contributor requirements for O3DE.
* The name under which the nominee should be addressed. Nominees are allowed to contact the election proctor to have this name changed.
* The GitHub username of the nominee (self-nominations need not include this; it's on your post.)
* Nominee's Discord username (sorry, but you must be an active Discord user if you are a chairperson.)

## Election process

The election will be conducted for one week from 2022-08-01 12 00PM PT and 2022-09-05 12:00PM PT and held through an online poll. Votes will be anonymous and anyone invested in the direction of O3DE and the SIG holding the election may vote. If you choose to vote, we ask that you be familiar with the nominees.

If there is a current interim chair, they will announce the results in the Discord SIG channel as well as the SIG O3DE mailing list no later than 2022-08-08 1:00PM PT. If there is no interim chair, the executive director will announce the results utilizing the same communication channels. At that time if there is a dispute over the result or concern over vote tampering, voting information will be made public to the extent that it can be exported from the polling system and the SIG will conduct an independent audit under the guidance of a higher governing body in the foundation.

The elected chairpersons will begin serving their term on 2022-08-09 at 10:00AM PT. Tentatively SIG chairs will be elected on a yearly basis.

**Comment by Ulrick28** [comment]
I nominate @tonybalandiuk for the role of Chair for the release sig.

**Comment by byrcolin** [comment]
I second the nomination of @tonybalandiuk for the role of Chair for the release sig.

**Comment by tonybalandiuk** [comment]
honored to be nominated @Ulrick28  and @byrcolin. I understand the responsibilities and requirements of the role, and promise to faithfully fulfill them and follow all contributor requirements for O3DE.

**Comment by Ulrick28** [comment]
I nominate @vincent6767 for co-chair.

**Comment by vincent6767** [comment]
Thanks for nominating me @Ulrick28! I understand the responsibilities and requirements of the role and promise to faithfully fulfill them and follow all contributor requirements for O3DE.

**Comment by rainbj** [comment]
+ for @tonybalandiuk and @vincent6767

**Comment by aFinchy** [comment]
Nominations have closed. Thank you all who have participated in the discussion.

Since there was only 2 members nominated there is no need to do a poll and since they have worked out who has what seat already, please welcome and congratulate the new chairs. 

@tonybalandiuk as Chair
@vincent6767 as Co-Chair

The Chair information will be updated in discord shortly. 

This Issue will remain open for 2 weeks following message.

**Comment by aFinchy** [comment]
Closing issue since there has been no issues that have come up. Thank you all who have participated.
