### ISSUE TITLE
Proposed RFC Suggestion =Add feature/viewport label=

### ISSUE THREAD

**Issue by hultonha** [o3de/sig-release#9]
# O3DE Suggestion RFC Template

### Summary:

Please can we add a `feature/viewport` label for O3DE (this exists in Jira on a more granular level but would be useful to help out team transition to GHI).

### What is the motivation for this suggestion?

To help filter/group viewport issues

### Are there any alternatives to this suggestion?

We could create more granular viewport features (e.g. `feature/viewport-interaction-model`, `feature/viewport-ui` etc...) but it might make things simpler to group everything under `feature/viewport`.

Attention of @forhalle

Thanks!

**Comment by mcphedar** [comment]
We have added the viewport label https://github.com/o3de/o3de/labels/feature%2Fviewport

**Comment by hultonha** [comment]
Thank you very much @mcphedar! Much appreciated :+1:
